spring:
  datasource:
    master:
      hikari:
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/master_db
    slave:
      hikari:
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/slave_db
